### ISSUE TITLE
BESS MGW pipeline direction

### ISSUE THREAD

**Issue by FedeParola** [hsnlab/tipsy#1]
Hello,
I'm using Tipsy to compare the performance of my MGW pipeline implemented in XDP with other technologies (currently bess).
According to the schema in the README file I have connected the uplink port of my tester to the downlink one of the SUT and vice-versa.
When I run a simple uplink test (generated packets in the pcap trace are directed from the user equipment to the remote server) packets on the sut are received on the donwlink port and then sent back on the same one.
This results in a measured RX bandwidth of 0.
I can overcome the problem swapping the uplink and downlink output ports in the bess mgw script.
Am I missing something?

**Comment by nemethf** [comment]
We had a discussion whether 'uplink' and 'downlink' where good descriptive terms because even we, the developers, used to mix up those.  So, it's probable that the bess version of MGW uses them wrongly. 

At any rate, can you show your complete configuration file (".tipsy.json")?

**Comment by FedeParola** [comment]
Here is my pipeline configuration:
[tipsy.txt](https://github.com/hsnlab/tipsy/files/4287510/tipsy.txt)

**Comment by nemethf** [comment]
So, the uplink traffic should arrive at dl_inport of SUT and exit via ul_outport.  @levaitamas, what do you think about the following patch?

```diff
diff --git a/bess/mgw.bess b/bess/mgw.bess
index 8e2b819..5635d2f 100644
--- a/bess/mgw.bess
+++ b/bess/mgw.bess
@@ -211,8 +211,8 @@ uttl_d -> dl_ws
 for wid in range(bess_workers):
   buf_u = Buffer(name='out_buf_u_%d' % wid)
   buf_d = Buffer(name='out_buf_d_%d' % wid)
-  ul_output = QueueOut(name="dl_outport_%d" % wid, port=portDL.name, qid=wid)
-  dl_output = QueueOut(name="ul_outport_%d" % wid, port=portUL.name, qid=wid)
+  ul_output = QueueOut(name="ul_outport_%d" % wid, port=portUL.name, qid=wid)
+  dl_output = QueueOut(name="dl_outport_%d" % wid, port=portDL.name, qid=wid)
   ul_ws:wid -> buf_u -> ul_output
   dl_ws:wid -> buf_d -> dl_output
```

**Comment by nemethf** [comment]
@FedeParola, it seems there's also an installation step that's not in the main README:
https://github.com/hsnlab/tipsy/blob/master/module/moongen/mg-pcap.lua#L20-L37

**Comment by levaitamas** [comment]
Thanks for reporting this issue @FedeParola!
Your patch makes sense, @nemethf. Let me send a PR fixing this and the [BNG pipeline](https://github.com/hsnlab/tipsy/blob/master/bess/bng.bess#L82) as well.
Also let me send an other PR to document the Moongen patch. Thanks.

**Comment by FedeParola** [comment]
Thanks for the support.
Another possible bug you may want to check out:
here
https://github.com/hsnlab/tipsy/blob/c21df9d0ddc5b1ad45c5197ec38053af946700d7/bess/mgw.bess#L197-L204
data paths for packets directed to next hops are set on gates from 1 to `conf.nhops` of the` ip_lookup` module, while here
https://github.com/hsnlab/tipsy/blob/c21df9d0ddc5b1ad45c5197ec38053af946700d7/bess/mgw.bess#L195
`srv.nhop` starts from 0.
This results in all packets that must go through first next hop to be indeed sent to the default route.

**Comment by nemethf** [comment]
Yeah, that seems strange as well.  @levaitamas?

At any rate, I'm closing this issue.  Please, open new ones if you find something else or just have questions.   Now reading the code, I realized the modularization wasn't finished, and I should have designed some parts completely differently.  But if you'd like to contribute your XDP implementation, we're here to help...
